//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRobotics
{
    [Serializable]
    public class VehicleDataMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_msgs/VehicleData";
        public override string RosMessageName => k_RosMessageName;

        public short steeringangle;
        public short motorleftforce;
        public short motorrightforce;
        public short breakforce;

        public VehicleDataMsg()
        {
            this.steeringangle = 0;
            this.motorleftforce = 0;
            this.motorrightforce = 0;
            this.breakforce = 0;
        }

        public VehicleDataMsg(short steeringangle, short motorleftforce, short motorrightforce, short breakforce)
        {
            this.steeringangle = steeringangle;
            this.motorleftforce = motorleftforce;
            this.motorrightforce = motorrightforce;
            this.breakforce = breakforce;
        }

        public static VehicleDataMsg Deserialize(MessageDeserializer deserializer) => new VehicleDataMsg(deserializer);

        private VehicleDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.steeringangle);
            deserializer.Read(out this.motorleftforce);
            deserializer.Read(out this.motorrightforce);
            deserializer.Read(out this.breakforce);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.steeringangle);
            serializer.Write(this.motorleftforce);
            serializer.Write(this.motorrightforce);
            serializer.Write(this.breakforce);
        }

        public override string ToString()
        {
            return "VehicleDataMsg: " +
            "\nsteeringangle: " + steeringangle.ToString() +
            "\nmotorleftforce: " + motorleftforce.ToString() +
            "\nmotorrightforce: " + motorrightforce.ToString() +
            "\nbreakforce: " + breakforce.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
