//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRobotics
{
    [Serializable]
    public class CameraServiceRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_msgs/CameraService";
        public override string RosMessageName => k_RosMessageName;

        public CameraMsg input;

        public CameraServiceRequest()
        {
            this.input = new CameraMsg();
        }

        public CameraServiceRequest(CameraMsg input)
        {
            this.input = input;
        }

        public static CameraServiceRequest Deserialize(MessageDeserializer deserializer) => new CameraServiceRequest(deserializer);

        private CameraServiceRequest(MessageDeserializer deserializer)
        {
            this.input = CameraMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "CameraServiceRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
