//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRobotics
{
    [Serializable]
    public class VehicleDataResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_msgs/VehicleData";
        public override string RosMessageName => k_RosMessageName;

        public VehicleDataMsg output;

        public VehicleDataResponse()
        {
            this.output = new VehicleDataMsg();
        }

        public VehicleDataResponse(VehicleDataMsg output)
        {
            this.output = output;
        }

        public static VehicleDataResponse Deserialize(MessageDeserializer deserializer) => new VehicleDataResponse(deserializer);

        private VehicleDataResponse(MessageDeserializer deserializer)
        {
            this.output = VehicleDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "VehicleDataResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
